using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace INVENTORYAPP.Migrations
{
    /// <inheritdoc />
    public partial class AddStockTransactionDetail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "dbo");

            migrationBuilder.CreateTable(
                name: "stocktransdet",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    slno = table.Column<int>(type: "int", nullable: true),
                    gord = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    doctype = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    DOCNO = table.Column<int>(type: "int", nullable: true),
                    mdoctype = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    sdoctype = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    docdate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    nfactor = table.Column<int>(type: "int", nullable: true),
                    nfactor2 = table.Column<int>(type: "int", nullable: true),
                    slno2 = table.Column<int>(type: "int", nullable: true),
                    stkcode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    stksubcode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    stkname = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    stkrefcode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    itemtype = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    mtltype = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    mtltype2 = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    karat = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    uom = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    mainuom = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    subuom = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    tranuom = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    lotno = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    gbatchno = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    orgbatchno = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    certno = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    mbarcode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    mtlcolor = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    diashape = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    stnshape = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    accode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    partycode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    suppcode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    refcode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    jobcode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    jobslno = table.Column<int>(type: "int", nullable: true),
                    jobno = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    settingcode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    lcccode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    loccode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    workercode = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    workername = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    nextworker = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    processcode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    processname = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    nextprocess = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    sman = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    pcs = table.Column<int>(type: "int", nullable: true),
                    pieces = table.Column<int>(type: "int", nullable: true),
                    qty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    grqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mainuqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    subuqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    tranuqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    transuqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    netgrqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalgrqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totgrqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    grweight = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalwt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    samplewt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    unitweight = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    puqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    newpuqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    puloss = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    pulossqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    lossgrqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    plqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mtlqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    stnqty = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    carats = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    stnpieces = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    diapieces = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    kbttbcount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    price = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    unitrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalrate = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    cost = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    costprice = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    netcost = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    nettotcost = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    rsprice = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    discperc = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    discamt = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    jobperc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    jobamount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgcost = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mtlrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mtlamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    amount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalamt = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    totalnetamt = table.Column<decimal>(type: "decimal(16,4)", precision: 16, scale: 4, nullable: true),
                    netamount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    taxableamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    taxamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    gtotalamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    lcamount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    fcamount = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    amountlc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgamtlc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mtlamtlc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalamtlc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgamtfc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mtlamtfc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    taxamtfc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    totalamtfc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    plamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    currcode = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    currrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    fccurr = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    currfc = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    currlc = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    usdrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    gozrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    purity = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    spurity = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    apurity = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    tspurity = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    directgold = table.Column<short>(type: "smallint", nullable: true),
                    trackno = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    trackslno = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    trackdate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    uniqueid = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    fromto = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    orderno = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    ordernumber = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    reportnumber = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    samplenumber = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    grlossgain = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    pulossgain = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    taxrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    mkgtaxamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    stnrate = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    stnamt = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    stnamtfc = table.Column<decimal>(type: "decimal(14,2)", precision: 14, scale: 2, nullable: true),
                    linenarration = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    hnarration = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    lnarration = table.Column<string>(type: "nvarchar(max)", maxLength: 5000, nullable: true),
                    purdoctype = table.Column<string>(type: "nvarchar(6)", maxLength: 6, nullable: true),
                    purdocno = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: true),
                    purslno = table.Column<int>(type: "int", nullable: true),
                    docrefno = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    docrefdate = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    stfdocno = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    issdocno = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    mfgdate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    prodtype = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    fixunfix = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    partytrn = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    impexptype = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    brncode = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    divcode = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    mdrcr = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    drcr = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    timestamp = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ts = table.Column<DateTime>(type: "datetime2", nullable: true),
                    stimestamp = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    usercode = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    isdeleted = table.Column<short>(type: "smallint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_stocktransdet", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "stocktransdet",
                schema: "dbo");
        }
    }
}
