// <auto-generated />
using System;
using INVENTORYAPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INVENTORYAPP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620133303_IntitalCreate")]
    partial class IntitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INVENTORYAPP.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<double?>("AddCess")
                        .HasColumnType("float");

                    b.Property<long?>("CatId")
                        .HasColumnType("bigint");

                    b.Property<double?>("CessPer")
                        .HasColumnType("float");

                    b.Property<decimal?>("CgstPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Deactivate")
                        .HasColumnType("bit");

                    b.Property<string>("DefBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HsnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IgstPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsExpiry")
                        .HasColumnType("bit");

                    b.Property<long?>("MainUnit")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManufId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Mrp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("PTaxIncl")
                        .HasColumnType("bit");

                    b.Property<string>("Rack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rol")
                        .HasColumnType("float");

                    b.Property<decimal?>("SRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("STaxIncl")
                        .HasColumnType("bit");

                    b.Property<decimal?>("SgstPer")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MST_ITEM", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
