using INVENTORYAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace INVENTORYAPP.Configurations;

public class ReceiptEntryDetailConfiguration
    : IEntityTypeConfiguration<ReceiptEntryDetail>
{
    public void Configure(
        EntityTypeBuilder<ReceiptEntryDetail> builder)
    {
        builder.ToTable("crcdet", "tradinguser");

        // ==========================================
        // Primary Key
        // ==========================================

        builder.HasKey(x => new
        {
            x.DocNo,
            x.SlNo
        });

        // Id generated by database
        builder.Property(x => x.Id)
            .ValueGeneratedOnAdd();

        // ==========================================
        // Receipt
        // ==========================================

        builder.Property(x => x.DocDate);

        builder.Property(x => x.STimestamp);

        // ==========================================
        // Party
        // ==========================================
        //
        // PartyId now stores AccountMaster.Id
        //
        // Allowed AccountMaster Actype:
        // C = Customer
        // S = Supplier
        //
        // No PartyMaster relationship.
        // ==========================================

        builder.Property(x => x.PartyId);

        // ==========================================
        // Account
        // ==========================================
        //
        // AccountId stores AccountMaster.Id
        //
        // Allowed AccountMaster Actype:
        // B = Bank/Cash
        // ==========================================

        builder.Property(x => x.AccountId);

        builder.HasOne(x => x.Account)
            .WithMany()
            .HasForeignKey(x => x.AccountId)
            .OnDelete(DeleteBehavior.Restrict);

        // ==========================================
        // Account Name
        // ==========================================

        builder.Property(x => x.AcName)
            .HasMaxLength(100);

        // ==========================================
        // Amount
        // ==========================================

        builder.Property(x => x.Amount)
            .HasPrecision(18, 2);

        // ==========================================
        // Receipt Header
        // ==========================================

        builder.HasOne(x => x.ReceiptEntry)
            .WithMany(x => x.Details)
            .HasForeignKey(x => x.DocNo)
            .OnDelete(DeleteBehavior.Cascade);
    }
}